apiVersion: v1 
kind: Service
metadata:
  name: nginx-service
spec:
  selector: 
    app: nginx
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    
    - name: metric
      port: 9113
      targetPort: 9113